#!/bin/sh

/usr/bin/setprop sys.powerctl shutdown
lxc-wait -n android -s "STOPPED" -t 30

# Teardown mapped super partition
if [ -e "/dev/disk/by-partlabel/super" ]; then
	dmsetup remove /dev/mapper/dynpart-* || true
fi

exit 0
